#!/bin/sh

set -eu

package_root=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
makevars="$package_root/src/Makevars"
generated_library="$package_root/src/libcompressor_pcodec_native.a"

rm -f -- "$generated_library" "$makevars"
