# Ingest fast paths must not change the stored bytes. Expected hashes were
# generated by the code before the fast paths were added (n = 1200 rows,
# threads = 2); every input type variant must reproduce them exactly.
ingest_variants <- function(n) {
  set.seed(5)
  chrs <- rep(c("1","2","10","22","X","Y"), length.out = n)
  pos <- sample.int(5e6, n) + 1000L
  b <- c("A","C","G","T"); r <- sample(4, n, TRUE); a <- (r + sample(3, n, TRUE) - 1L) %% 4L + 1L
  se <- runif(n, .01, .1); beta <- rnorm(n, 0, .05)
  base <- data.frame(chromosome = chrs, base_pair_location = pos,
    reference_allele = b[r], alternate_allele = b[a], effect_allele = b[a], other_allele = b[r],
    beta = beta, standard_error = se, effect_allele_frequency = runif(n, .05, .95),
    p_value = 2*pnorm(-abs(beta/se)), stringsAsFactors = FALSE)
  messy <- function(x) { i <- seq(1, n, 7); x[i] <- tolower(x[i]); j <- seq(2, n, 11); x[j] <- paste0(" ", x[j], " "); x }
  v <- list(base = base)
  d <- base; d$base_pair_location <- as.double(d$base_pair_location); v$pos_double <- d
  d <- base; d$base_pair_location <- as.character(d$base_pair_location); v$pos_char <- d
  d <- base; d$base_pair_location <- factor(d$base_pair_location); v$pos_factor <- d
  d <- base; for (f in c("reference_allele","alternate_allele","effect_allele","other_allele")) d[[f]] <- messy(d[[f]]); v$messy_alleles <- d
  d <- base; for (f in c("reference_allele","alternate_allele","effect_allele","other_allele")) d[[f]] <- factor(messy(d[[f]])); v$factor_alleles <- d
  d <- base; d$chromosome <- paste0(rep(c("chr","Chr",""), length.out = n), d$chromosome); v$chr_prefix <- d
  d <- base; d$chromosome <- factor(paste0("chr", d$chromosome)); v$chr_factor <- d
  d <- base; d$chromosome <- ifelse(d$chromosome %in% c("X"), "23", ifelse(d$chromosome == "Y", "24", d$chromosome)); v$chr_alias <- d
  d <- base; d$chromosome <- ifelse(d$chromosome %in% as.character(1:22), d$chromosome, "1"); d$chromosome <- as.integer(d$chromosome); v$chr_integer <- d
  d <- base; d$p_value <- as.character(d$p_value); v$p_char <- d
  d <- base; d$p_value[seq(3, n, 13)] <- NA; v$p_na <- d
  d <- base; d$p_value[seq(3, n, 13)] <- NA; d$p_value <- as.character(d$p_value); d$p_value[seq(5, n, 17)] <- "NA"; d$p_value[seq(6, n, 19)] <- "."; v$p_char_na <- d
  d <- base; d$base_pair_location[c(2, 9)] <- c(1e9, 0); v$pos_bad <- d
  d <- base; d$base_pair_location <- as.double(d$base_pair_location); d$base_pair_location[c(2,9)] <- c(1000.5, NA); v$pos_frac_na <- d
  d <- base; d$chromosome[4] <- "MT"; d$reference_allele[6] <- "AT"; d$alternate_allele[8] <- NA; v$bad_rows <- d
  d <- base; d$chromosome[3] <- NA; v$chr_na <- d
  v
}

ingest_expected <- data.frame(
  variant = c("base", "base", "pos_double", "pos_double", "pos_char", "pos_char", "pos_factor", "pos_factor", "messy_alleles", "messy_alleles", "factor_alleles", "factor_alleles", "chr_prefix", "chr_prefix", "chr_factor", "chr_factor", "chr_alias", "chr_alias", "chr_integer", "chr_integer", "p_char", "p_char", "p_na", "p_na", "p_char_na", "p_char_na", "pos_bad", "pos_bad", "pos_frac_na", "pos_frac_na", "bad_rows", "bad_rows", "chr_na", "chr_na"),
  qc = c("none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact", "none", "compact"),
  rows = c(1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200, 1198, 1198, 1198, 1198, 1197, 1197, 1199, 1199),
  payload = c(
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "123e98599691dd771a79c6ceb1405c5776d8ce139b6330cc4d089e7a72a64579",
    "123e98599691dd771a79c6ceb1405c5776d8ce139b6330cc4d089e7a72a64579",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "fed1349d23ac4177799555cd415b12d44bdc64074f81ec024f9dfbde08812572",
    "3f2c80988d84a2cac3d47930aa2597d1872217f6fadd84f32717cfbce9fe3e41",
    "3f2c80988d84a2cac3d47930aa2597d1872217f6fadd84f32717cfbce9fe3e41",
    "3f2c80988d84a2cac3d47930aa2597d1872217f6fadd84f32717cfbce9fe3e41",
    "3f2c80988d84a2cac3d47930aa2597d1872217f6fadd84f32717cfbce9fe3e41",
    "83238225f3b03e0bd7a8b73d93fc178d07c3a3fbb7d7f870c00bb2e62191ab01",
    "83238225f3b03e0bd7a8b73d93fc178d07c3a3fbb7d7f870c00bb2e62191ab01",
    "401f7120aa4eba766576be346acc2350c87959a1aa57ea8c4e0ab615ead6a815",
    "401f7120aa4eba766576be346acc2350c87959a1aa57ea8c4e0ab615ead6a815"),
  canonical = c(
    "1f0ca9471ac87cc4f3e720a91efc92db72e3b08c3e1317574d917bc3fd2f4e2c",
    "9546520ad6d5c350838b780c68b90c9c9c6c1dbe9cf7d1f899af3e5535a960ed",
    "6b16024fef88d0ff5f1159d05e90b3e5f20353793f03c01bd6b225ee86ab962f",
    "ec97ab5eb1c0d86b3214a65cfeca7a48919def0e4143f0c53eac0648e78b9f8b",
    "edd30ed4fa646600d9ceb2fc9080d98835059cbcd9367b8339440a4d1b69957e",
    "d5d4714e0342628a4ed2e0d5bd385be111d62cab9f060472f203515f03e8c537",
    "52c96557fce1f3499caf89085f31cf9ffc242ca58c29100b4e2b3303303ae133",
    "e93ea51866ab95dbc24877087b83b9594dccaffba859d6e41dc8e3f53e651c1a",
    "6a9e4ce273b9e66e244c91d57d7890b6d0793cfd9ce4504139c475e4ae3b9f7e",
    "47a494a3636748356a030bc037f6e36de8bf7d96e069fb259dd2b87c4bb21490",
    "6b3119333b9fa0b471748db204b1e8256db41e3d6550d425108cbad976d2bbef",
    "dddc419c1e0a08826ac9767874f46d8ab2ff56a1bbfc30c400db167393d6a607",
    "8c18a41d3ccd08d6d53defefa67be9f49d2b6d375e2d6dcb9eacc67955f2c9b2",
    "4e8b5a45c51a965a1248574b69aad9a03f02b2cdd0ec0771d1ebc9bb89d75226",
    "bbe58910fddd3ea337036317a8d38085aebf7b4d2b37c9407cae8d364fea372b",
    "e2c7732d2e1889ffe183197a353aca70d54f03bd96bccd767380c6286d9e55e2",
    "33c5e9f58074c83e4c43e69238ef7f758d64a4bea3ab2ef59af73195ea8d88c9",
    "9c9ff4f7941910e8b1e581d2a479da4c3bd919fe995edcbff9960c9f270fb85d",
    "35ce1d1395bc1ce3ab535bd542d7c00ba2dbb1547eb866a8d826841ab11e7237",
    "1d319207d7fbb91977b3eba15b6349d36c36675a85eefc0183da7fa0082835fb",
    "327ade2c1eec4832b62e8369ec71554ab72e226d25fca6fcf57685d4430d6a04",
    "806e78f6b598ca1660594725d4cd1e9e53893ea1cd091630820b365369c757ae",
    "bc7a8857293a5fe426cd125d960fe1baa320da2b17c0c6015fc63c6077d3da87",
    "e7837df66f62876e12ec018ad5f8171e041e522fe4f24e3ece20f3bc56a3401c",
    "b789d6cf585e3b4a00fda2a91b8e84b6f9aeae67c4ddbe025f72df3e7d35b48c",
    "c09ad9db51007cdb3b1ecd513d7dfc4bd279d7c02d87f391aa03ea96d176afd7",
    "85cd877821ac132122a84109c7f848a1030d7a4c871a74f1b8185a9de1c4a7b0",
    "b3437de046db6e6d32126f7595515c6344cafd89fff039edd4c810160b971cca",
    "7ebd4d10c76b9b723b563c9aa51a191d6285fa8f5541b3cf87aeafcc04521e1e",
    "7d2ea514811f8610a1c144405ec8de1f2eb41a25f232642f25096afcc360cfad",
    "91405ac2d093cbca7d19e1100138b196718c3259dff16f1882465fbc62ea57d5",
    "7fd1163caf2b0fec4c34c575b4cc274b02f111264f69b1cd59fc7d8ec9b6ddb2",
    "b628ff8066bcd662b830d1431e8a0c2ac1731a7b6537310312ab4128ec9c6c63",
    "1ab374bf9f07e214258cfbf23bade83961beac04f0e098dbc28b658de268ccc2"),
  stringsAsFactors = FALSE
)

ingest_store_hashes <- function(data, qc) {
  path <- tempfile("ingest-fastpath-", fileext = ".cpr")
  on.exit(unlink(path, recursive = TRUE), add = TRUE)
  # The pinned payload hashes were recorded with the Z9/SE6 profile; the
  # ingest paths under test are independent of the quantisation profile.
  old <- options(CompreSSoR.native_profile = "z9/eaf8/se6")
  on.exit(options(old), add = TRUE)
  store <- suppressWarnings(compress_sumstats(data, path, qc = qc, overwrite = TRUE, pvalue_order = FALSE,
                                              threads = 2L))
  list(rows = store$manifest$n_rows,
       payload = store$manifest$integrity$payload_sha256,
       canonical = store$manifest$integrity$canonical_sha256)
}

test_that("ingest type variants reproduce pre-optimisation store hashes", {
  skip_if_not(CompreSSoR:::pcodec_native_available(),
              "native Pcodec backend is not built")
  variants <- ingest_variants(1200L)
  for (k in seq_len(nrow(ingest_expected))) {
    e <- ingest_expected[k, ]
    got <- ingest_store_hashes(variants[[e$variant]], e$qc)
    label <- paste(e$variant, e$qc)
    expect_identical(as.integer(got$rows), as.integer(e$rows), label = label)
    # Pin the stored data by payload hash. The canonical manifest hash embeds a
    # serialize() digest of the input, which differs across R versions (and for
    # factor columns across sessions), so it is not pinned here.
    expect_identical(got$payload, e$payload, label = label)
  }
})

test_that("equivalent input encodings give identical payloads", {
  skip_if_not(CompreSSoR:::pcodec_native_available(),
              "native Pcodec backend is not built")
  variants <- ingest_variants(1200L)
  ref <- ingest_store_hashes(variants$base, "none")$payload
  for (v in c("pos_double", "pos_char", "pos_factor", "messy_alleles",
              "factor_alleles", "chr_prefix", "chr_factor", "chr_alias",
              "p_char", "p_na", "p_char_na")) {
    for (qc in c("none", "compact")) {
      expect_identical(ingest_store_hashes(variants[[v]], qc)$payload, ref,
                       label = paste(v, qc))
    }
  }
})

test_that("fast-path helpers match the character round trip", {
  slow_num <- function(x) suppressWarnings(as.numeric(as.character(x)))
  cases <- list(
    1:100, as.double(1:100), c(1, 2.5, NA, 3), c(1e15, 1), c(1e8 + 1e-8, 5),
    c(Inf, -Inf, NaN, 4), factor(c("10", "20", "x")), c("1", " 2", "3e2"),
    c(0.1 + 0.2, 1 + 1e-15), rep(c(1, NA), 50)
  )
  for (x in cases) {
    expect_identical(CompreSSoR:::coordinate_as_numeric(x), slow_num(x))
    # statistic_as_numeric() is only used for range tests: classification must agree.
    a <- CompreSSoR:::statistic_as_numeric(x); b <- slow_num(x)
    expect_identical(is.finite(a) & a > 0, is.finite(b) & b > 0)
    expect_identical(is.finite(a) & a >= 0 & a <= 1, is.finite(b) & b >= 0 & b <= 1)
  }
  alleles <- rep(c(" a", "C ", "g", "T", NA, "ac", "", " "), 20)
  slow_all <- function(x) toupper(trimws(as.character(x)))
  expect_identical(CompreSSoR:::normalise_allele_vector(alleles), slow_all(alleles))
  expect_identical(CompreSSoR:::normalise_allele_vector(factor(alleles)),
                   slow_all(factor(alleles)))
  chr <- rep(c("chr1", "CHR2", " 23", "24", "M", "x", ".", "NA", NA, ""), 10)
  slow_chr <- function(x) {
    out <- toupper(trimws(sub("^chr", "", as.character(x), ignore.case = TRUE)))
    out[out == "23"] <- "X"; out[out == "24"] <- "Y"
    out[out %in% c("M", "25", "26")] <- "MT"
    out[out %in% c("", ".", "NA")] <- NA_character_
    out
  }
  expect_identical(CompreSSoR:::normalise_chromosome(chr), slow_chr(chr))
  expect_identical(CompreSSoR:::normalise_chromosome(factor(chr)), slow_chr(chr))
  expect_error(CompreSSoR:::compressor_normalize_chromosome(rep(c("1", "MT"), 40)),
               "chromosome must be one of 1-22, X, Y")
})
